# FILE: backend/app/ai/coaching_engine.py
"""
CoachingEngine — generate coaching feedback using LLM + RAG.

Orchestrates:
  1. Load module version, rubric, prompt template
  2. Retrieve relevant knowledge chunks via RAG
  3. Build prompt with PromptBuilder
  4. Call LLM via OllamaClient for feedback text
  5. Safety-check the model's own output (SafetyEngine)
  6. Call ScoringEngine for real, model-generated rubric scores
  7. Return CoachingResponse

The engine handles LLM parsing errors by wrapping them in UnprocessableError.
"""
from __future__ import annotations

import json
import re
import time
from uuid import UUID

from app.ai.ollama_client import OllamaClient
from app.ai.prompt_builder import PromptBuilder
from app.ai.safety_engine import SafetyEngine
from app.ai.scoring_engine import ScoringEngine
from app.core.exceptions import ContentSafetyError, NotFoundError, UnprocessableError
from app.database.unit_of_work import UnitOfWork
from app.rag.citation_service import CitationService
from app.rag.retrieval_service import RetrievalService
from app.schemas.ai.coaching import CoachingResponse


class CoachingEngine:
    """Generate AI coaching feedback with RAG context."""

    def __init__(
        self,
        ollama_client: OllamaClient,
        prompt_builder: PromptBuilder,
        retrieval_service: RetrievalService,
        citation_service: CitationService,
        scoring_engine: ScoringEngine | None = None,
        safety_engine: SafetyEngine | None = None,
    ) -> None:
        """
        Initialize coaching engine.

        Args:
            ollama_client: LLM client for generation
            prompt_builder: service for resolving prompt templates
            retrieval_service: service for RAG retrieval
            citation_service: service for formatting citations
            scoring_engine: LLM-based rubric scorer. Defaults to a ScoringEngine
                sharing this engine's LLM client and prompt builder, so scores
                are actually generated by the model rather than by keyword
                counting.
            safety_engine: content safety checker run on the model's own
                feedback output before it's returned. Defaults to a fresh
                SafetyEngine instance.
        """
        self._ollama = ollama_client
        self._prompt_builder = prompt_builder
        self._retrieval = retrieval_service
        self._citations = citation_service
        self._scoring = scoring_engine or ScoringEngine(
            ollama_client=ollama_client, prompt_builder=prompt_builder
        )
        self._safety = safety_engine or SafetyEngine()

    async def generate_feedback(
        self,
        session_id: UUID,
        user_id: UUID,
        module_version_id: UUID,
        tenant_id: UUID | None,
        intake_data: dict[str, str],
    ) -> CoachingResponse:
        """
        Generate coaching feedback for a session.

        Args:
            session_id: coaching session UUID
            user_id: learner UUID
            module_version_id: module version UUID
            tenant_id: tenant UUID — scopes both RAG retrieval AND the
                       UnitOfWork used to load the module version, so RLS
                       (migration 011) actually applies here.
            intake_data: learner's intake form submission

        Returns:
            CoachingResponse with feedback, scores, citations

        Raises:
            NotFoundError: when module version not found
            UnprocessableError: when LLM generation or parsing fails
            ContentSafetyError: when the model's own feedback output fails
                a safety check
        """
        start_time = time.time()

        # Load module version and related data — tenant-scoped so this
        # doesn't silently return nothing under fail-closed RLS.
        async with UnitOfWork(tenant_id=tenant_id) as uow:
            module_version = await uow.module_versions.get_version_with_definition(module_version_id)
            if not module_version:
                raise NotFoundError(f"ModuleVersion {module_version_id} not found")

            # Retrieve knowledge chunks if tenant context available
            chunks = []
            if tenant_id:
                query_text = " ".join(intake_data.values())

                chunk_results = await self._retrieval.retrieve(
                    query=query_text,
                    tenant_id=tenant_id,
                    module_id=module_version.module_id,
                    uow=uow,
                )
                chunks = chunk_results

            # Build knowledge context
            knowledge_context = self._citations.build_context_text(chunks)
            knowledge_chunks = [knowledge_context] if chunks else []

            # Build prompt
            template = self._get_default_coaching_template()

            prompt = self._prompt_builder.build_coaching_prompt(
                template=template,
                intake_data=intake_data,
                rubric=module_version.scoring_rubric or {},
                knowledge_chunks=knowledge_chunks,
                framework_name=module_version.framework_name,
            )

            # Generate feedback text with LLM
            import logging as _log
            _logger = _log.getLogger("ai_coach.coaching_engine")
            _logger.info("[CE] Calling Ollama generate...")
            llm_response = await self._ollama.generate(
                prompt=prompt,
                system="You are an expert executive coach providing constructive feedback.",
            )
            _logger.info(f"[CE] Ollama responded — content length={len(llm_response.content)}")

            # Parse feedback response (text + strengths/improvements only — NOT scores)
            try:
                parsed = self._parse_feedback_response(llm_response.content)
            except Exception as exc:
                _logger.error(f"[CE] PARSE FAILED: {type(exc).__name__}: {exc}")
                import traceback
                _logger.error(f"[CE] TRACEBACK:\n{traceback.format_exc()}")
                raise UnprocessableError(
                    f"Failed to parse LLM response: {exc}"
                ) from exc

            # Safety check on the model's own output — enforced by the
            # engine itself, not left to prompt wording, per PRD A.4/B.5.
            from app.ai.safety_engine import SafetyEngine as _SafetyEngine
            from app.core.exceptions import ContentSafetyError as _ContentSafetyError
            from app.repositories.analytics.analytics_repository import AuditLogCreate

            _safety_check = await _SafetyEngine().check_content(parsed["feedback_text"])
            if not _safety_check.is_safe:
                _logger.error(
                    f"[CE] SAFETY BLOCK on feedback output — session={session_id} "
                    f"category={_safety_check.category}"
                )
                try:
                    await uow.analytics.write_audit_log(
                        AuditLogCreate(
                            action="CONTENT_SAFETY_BLOCK",
                            entity_type="coaching_session",
                            entity_id=session_id,
                            actor_user_id=user_id,
                            tenant_id=tenant_id,
                            after_state={
                                "category": _safety_check.category,
                                "reason": _safety_check.reason,
                            },
                        )
                    )
                    await uow.commit()
                except Exception as audit_exc:
                    _logger.error(f"[CE] Failed to write safety audit log: {audit_exc}")
                # NOTE: crisis-category handling for AI OUTPUT is
                # intentionally still a hard rejection, not a supportive
                # message — this is model-generated text failing its own
                # check, not the learner expressing distress. Learner-
                # authored crisis language is handled separately in the
                # router layer (see sessions.py), which is where a
                # supportive response actually belongs.
                raise _ContentSafetyError(
                    "Generated feedback did not pass a safety check and could "
                    "not be delivered."
                )

            # Score the feedback against the rubric using a SEPARATE, real LLM
            # call (low temperature) — each rubric dimension gets its own
            # model-assessed score + rationale, not a keyword-frequency guess.
            score_response = await self._scoring.score_session(
                session_id=session_id,
                feedback_text=parsed["feedback_text"],
                rubric=module_version.scoring_rubric or {},
                intake_data=intake_data,
            )

            scores = {
                dim.dimension_name: {
                    "score": dim.score,
                    "rationale": dim.rationale,
                }
                for dim in score_response.score_breakdown.dimensions
            }
            overall_score = score_response.score_breakdown.overall_score

            # Format citations
            citations = self._citations.format_citations(chunks)

            end_time = time.time()
            generation_time_ms = int((end_time - start_time) * 1000)

            return CoachingResponse(
                session_id=session_id,
                feedback_text=parsed["feedback_text"],
                scores=scores,
                overall_score=overall_score,
                strengths=parsed["strengths"],
                improvements=parsed["improvements"],
                recommendations=parsed["recommendations"],
                next_steps=parsed.get("next_steps"),
                citations=citations,
                knowledge_used=len(chunks) > 0,
                raw_ai_response=llm_response.content,
                generation_metadata={
                    "prompt_tokens": llm_response.prompt_tokens,
                    "completion_tokens": llm_response.completion_tokens,
                    "response_time_ms": llm_response.response_time_ms,
                    "model_used": llm_response.model_used,
                    "generation_time_ms": generation_time_ms,
                },
            )

    def _get_default_coaching_template(self) -> str:
        return """You are an expert coach. Review this {{framework}} feedback submission and respond with ONLY a JSON object.

Submission:
Situation: {{situation}}
Behaviour: {{behaviour}}
Impact: {{impact}}

Respond with ONLY this JSON (no other text):
{"feedback_text":"2-3 sentences of constructive coaching feedback","strengths":["one strength"],"improvements":["one improvement area"],"recommendations":[{"priority":1,"area":"key skill","suggestion":"specific actionable tip"}],"next_steps":"one concrete next step"}"""

    def _parse_feedback_response(self, response: str) -> dict:
        """
        Parse the LLM's feedback JSON.

        NOTE: this no longer computes rubric scores — those come from a
        dedicated ScoringEngine.score_session() LLM call in generate_feedback()
        so each rubric dimension gets its own model-assessed score.
        """
        import logging as _log
        _logger = _log.getLogger("ai_coach.coaching_engine")
        _logger.info(f"[PARSE] Starting parse — response length={len(response)}")

        json_match = re.search(r"```json\s*(\{.*?\})\s*```", response, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            json_match = re.search(r"\{.*\}", response, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
            else:
                _logger.error(f"[PARSE] NO JSON FOUND IN RESPONSE")
                raise ValueError("No JSON object found in response")

        try:
            parsed = json.loads(json_str)
        except json.JSONDecodeError as exc:
            _logger.error(f"[PARSE] JSON PARSE FAILED: {exc}")
            raise ValueError(f"Invalid JSON in response: {exc}") from exc

        feedback_text = parsed.get("feedback_text", "")
        if not feedback_text:
            raise ValueError("Missing feedback_text in response")

        strengths = parsed.get("strengths", [])
        improvements = parsed.get("improvements", [])
        recommendations = parsed.get("recommendations", [])
        next_steps = parsed.get("next_steps")

        return {
            "feedback_text": feedback_text,
            "strengths": strengths,
            "improvements": improvements,
            "recommendations": recommendations,
            "next_steps": next_steps,
        }